### ISSUE TITLE
使用过程中遇到了一些问题

### ISSUE THREAD

**Issue by LKarrie** [alexzzh/ngx_http_health_detect_module#11]
首先感谢您贡献出这么优秀的三方模块；

个人测试之后健康检查功能没有发现异常，但是在普通配置中发现了一些问题，下面是测试终端的复制内容
```terminal
[nginx@nginx conf.d]$ /app/nginx/sbin/nginx -V
nginx version: nginx/1.20.2
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/app/nginx --with-compat --with-file-aio --with-threads --with-http_ssl_module --with-stream --with-stream_ssl_module --with-http_sub_module --add-module=/app/nginx_build/module/ngx_health_detect_module
[nginx@nginx conf.d]$ cat test.conf 

server {
        listen 8080;
        location / {
                return 200 "hello\n";
        }
}


server {
        listen 8081;
        location / {
                proxy_pass http://127.0.0.1:8080;
        }
}
[nginx@nginx conf.d]$ curl -i http://127.0.0.1:8080
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 02 Aug 2023 07:33:20 GMT
Content-Type: application/octet-stream
Content-Length: 6
Connection: keep-alive

hello
[nginx@nginx conf.d]$ curl -i http://127.0.0.1:8081
HTTP/1.1 502 Bad Gateway
Server: nginx
Date: Wed, 02 Aug 2023 07:33:25 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 150
Connection: keep-alive
```
查看日志之后发现 变量 $upstream_addr 直接输出 127.0.0.1 而不是 127.0.0.1:8080 ;
看起来增加了健康检查的模块后影响到了这里，proxy_pass 后的地址都把端口截断了，默认访问80；
另外 readme中 peer_type 应该调整为 type。

**Comment by qazhub** [comment]
这个问题依然存在。所有使用 `proxy_pass` 指令的地方，自定义端口都会被丢弃，导致无法将请求代理到后端。

**Comment by alexzzh** [comment]
> 首先感谢您贡献出这么优秀的三方模块；
> 
> 个人测试之后健康检查功能没有发现异常，但是在普通配置中发现了一些问题，下面是测试终端的复制内容
> 
> ```
> [nginx@nginx conf.d]$ /app/nginx/sbin/nginx -V
> nginx version: nginx/1.20.2
> built by gcc 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
> built with OpenSSL 1.0.2k-fips  26 Jan 2017
> TLS SNI support enabled
> configure arguments: --prefix=/app/nginx --with-compat --with-file-aio --with-threads --with-http_ssl_module --with-stream --with-stream_ssl_module --with-http_sub_module --add-module=/app/nginx_build/module/ngx_health_detect_module
> [nginx@nginx conf.d]$ cat test.conf 
> 
> server {
>         listen 8080;
>         location / {
>                 return 200 "hello\n";
>         }
> }
> 
> 
> server {
>         listen 8081;
>         location / {
>                 proxy_pass http://127.0.0.1:8080;
>         }
> }
> [nginx@nginx conf.d]$ curl -i http://127.0.0.1:8080
> HTTP/1.1 200 OK
> Server: nginx
> Date: Wed, 02 Aug 2023 07:33:20 GMT
> Content-Type: application/octet-stream
> Content-Length: 6
> Connection: keep-alive
> 
> hello
> [nginx@nginx conf.d]$ curl -i http://127.0.0.1:8081
> HTTP/1.1 502 Bad Gateway
> Server: nginx
> Date: Wed, 02 Aug 2023 07:33:25 GMT
> Content-Type: text/html; charset=UTF-8
> Content-Length: 150
> Connection: keep-alive
> ```
> 
> 查看日志之后发现 变量 $upstream_addr 直接输出 127.0.0.1 而不是 127.0.0.1:8080 ; 看起来增加了健康检查的模块后影响到了这里，proxy_pass 后的地址都把端口截断了，默认访问80； 另外 readme中 peer_type 应该调整为 type。

非常感谢你指出该问题。

在我们的生产环境，一直都使用upstream块，配合负载均衡策略以及其他三方模块一起使用，所以没及时发现该问题，目前该问题已修复。

**Comment by alexzzh** [comment]
> peer_type

已修复 https://github.com/alexzzh/ngx_health_detect_module/pull/18

**Comment by alexzzh** [comment]
> 这个问题依然存在。所有使用 `proxy_pass` 指令的地方，自定义端口都会被丢弃，导致无法将请求代理到后端。

fixed on https://github.com/alexzzh/ngx_health_detect_module/pull/18
