### ISSUE TITLE
是否可以适配 tengine

### ISSUE THREAD

**Issue by v55448330** [alexzzh/ngx_http_health_detect_module#13]

**Comment by v55448330** [comment]
我在 Tengine 3.1.0 中 patch 失败

**Comment by alexzzh** [comment]
你好，可以根据 https://github.com/alexzzh/ngx_health_detect_module/blob/master/README-zh.md#%E5%88%B6%E4%BD%9Cpatch 这个说明，快速制作 tengine 的patch。 如果愿意，可以把制作好的patch上传至本仓库以供其他同学使用。
