### ISSUE TITLE
nginx版本1.26下编译失败

### ISSUE THREAD

**Issue by reminisences** [alexzzh/ngx_http_health_detect_module#20]
在nginx最新版本1.26下引用nginx_healthdetect_for_nginx_1.24+.patch编译失败，同时也看了制作patch的命令，当运行到命令 
diff * > nginx_healthdetect_for_nginx_x.xx+.patch也是直接失败，我感觉制作补丁这一套命令下来，应该是有问题的吧，直接在nginx目录下运行diff * > nginx_healthdetect_for_nginx_x.xx+.patch，总感觉怪怪的，我猜想diff命令应该和某个文件/文件夹比较之后有差异才能打出补丁文件吧。
以上,希望解决疑惑，谢谢。

**Comment by reminisences** [comment]
制作新脚本搞不定，但是直接引用1.24+的补丁，还是可以的。虽然有几个小错误，我修复了见 PR #21 。希望作者能告诉我这个小白制作新补丁的完整命令行,感谢.

**Comment by alexzzh** [comment]
> 制作新脚本搞不定，但是直接引用1.24+的补丁，还是可以的。虽然有几个小错误，我修复了见 PR #21 。希望作者能告诉我这个小白制作新补丁的完整命令行,感谢.

LGTM ，如果编译时指定 NGX_DEBUG， 会出现PR中的编译错误，已合并

已上传基于nginx1.26+的patch，制作方案详见:
https://github.com/alexzzh/ngx_health_detect_module/pull/24

**Comment by reminisences** [comment]
> > 制作新脚本搞不定，但是直接引用1.24+的补丁，还是可以的。虽然有几个小错误，我修复了见 PR #21 。希望作者能告诉我这个小白制作新补丁的完整命令行,感谢.
> 
> LGTM ，如果编译时指定 NGX_DEBUG， 会出现PR中的编译错误，已合并
> 
> 已上传基于nginx1.26+的patch，制作方案详见: #24

完美运行，非常感谢！！！

**Comment by reminisences** [comment]
> > 制作新脚本搞不定，但是直接引用1.24+的补丁，还是可以的。虽然有几个小错误，我修复了见 PR #21 。希望作者能告诉我这个小白制作新补丁的完整命令行,感谢.
> 
> LGTM ，如果编译时指定 NGX_DEBUG， 会出现PR中的编译错误，已合并
> 
> 已上传基于nginx1.26+的patch，制作方案详见: #24

完美运行，非常感谢！！！
