### ISSUE TITLE
master进程存在内存泄漏

### ISSUE THREAD

**Issue by Sunldon** [alexzzh/ngx_http_health_detect_module#28]
master进程中调用了ngx_http_health_detect_add_or_update_node_on_local，并创建了内存池
`    temp_pool = ngx_create_pool(
        ngx_align(peer_size + peer_policy_max_size, ngx_cacheline_size),
        ngx_cycle->log);`
当reload nginx时，这部分内存分配的node节点不会释放，会继续创建新的内存池，继续新的分配
解决办法是在ngx_http_health_detect_create_main_conf中调用ngx_http_health_detect_delete_all_node()
`static void *
ngx_http_health_detect_create_main_conf(ngx_conf_t *cf)
{
    ngx_http_health_detect_main_conf_t *hdmcf;
    ngx_health_detect_peers_t *peers;
    ngx_http_health_detect_delete_all_node();

}`

**Comment by Sunldon** [comment]
#31 提交了相关修改，不过并不是调用ngx_http_health_detect_delete_all_node，而是调用ngx_http_health_detect_clear_peers_events进行释放内存

**Comment by alexzzh** [comment]
非常感谢您的反馈！

这里想了解下，你这边观察到的现象是什么，比如进程内存占用持续升高等，可以贴一下问题现象，以便进一步确认，再次感谢。
