### ISSUE TITLE
为什么需要使用shm共享内存？

### ISSUE THREAD

**Issue by Sunldon** [alexzzh/ngx_http_health_detect_module#30]
peers_shm主要是存储节点状态，是否健康检查成功。
是否可以取消共享内存的时候，减少锁的使用，跟peers一样，每个进程独享一份数据？
可能每个进程健康检查的结果会有差异，如果后端节点不通，每个子进程的健康检查都会更新到各自的状态存储数据中，按道理来说也不会有太大的问题。

**Comment by alexzzh** [comment]
其实就是为了确保各进程的健康检查状态的一致性。因为查询健康状态接口请求可能会被任意进程处理，如果不使用共享内存，就会导致多次健康状态接口请求的结果不一致，探测节点由异常切换为正常时，连续调用状态接口可能会依次返回up->down->up, 调用方可能会认为该节点曾经up再down过，影响调用方的判断，这种误差在节点数多以及探测间隔时间比较长时尤为明显。
