### ISSUE TITLE
Patch for 1.19+ is corrupt

### ISSUE THREAD

**Issue by mmoya** [alexzzh/ngx_http_health_detect_module#8]
At least the patch for 1.19+ is corrupt. Maybe the trailing spaces were mangled as part of #6.
```
~/src/gh/n/nginx branches/stable-1.24 [$?]
$ patch -p1 <../../alexzzh/ngx_health_detect_module/patch/nginx_healthdetect_for_nginx_1.19+.patch
patching file src/http/modules/ngx_http_upstream_hash_module.c
patch: **** malformed patch at line 28: @@ -560,6 +571,15 @@ ngx_http_upstream_get_chash_peer(ngx_peer_connection_t *pc, void *data)
```

**Comment by alexzzh** [comment]
Hi mmoya,  thanks to your reminding. 
I only tested  nginx_healthdetect_for_nginx_1.12+.patch file in "patch" directory before, so you found this corrupt.   now, I  have adapted to nginx_healthdetect_for_nginx_1.16+.patch and  nginx_healthdetect_for_nginx_1.18+.patch for more people to use.
see [MR](https://github.com/alexzzh/ngx_health_detect_module/pull/9).
